site_name: Formeo
site_url: http://draggable.github.io/formeo/
repo_url: https://github.com/Draggable/formeo.git
repo_name: 'GitHub'
site_description: A highly configurable drag & drop form building module written in pure JavaScript.
site_favicon: favicon.ico
theme: readthedocs
pages:
- Introduction: index.md
- Options: options.md
- Demos:
  - Basic: demos/basic.md
- About:
  - License: license.md
extra_css:
  - 'css/site.css'
  - '//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/monokai-sublime.min.css'
extra_javascript:
  - 'js/scripts.js'
  - '//assets.codepen.io/assets/embed/ei.js'
  - '//sidecar.gitter.im/dist/sidecar.v1.js'
